// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using diji_card_alt.Data;

#nullable disable

namespace digitalbusinesscard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250907212019_AddIsSpecialAccessToProfileVisits")]
    partial class AddIsSpecialAccessToProfileVisits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalBusinessCard.Models.PrivateProfileAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("IX_PrivateProfileAccess_AccessToken");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PrivateProfileAccess_UserId");

                    b.ToTable("PrivateProfileAccesses");
                });

            modelBuilder.Entity("DigitalBusinessCard.Models.UserPreferences", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FontFamily")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Inter");

                    b.Property<int>("GridColumns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("ThemeColor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("orange");

                    b.Property<string>("ViewMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("list");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("diji_card_alt.Models.Definition", b =>
                {
                    b.Property<int>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DefinitionId"));

                    b.Property<string>("DefinitionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DefinitionId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("diji_card_alt.Models.ProfileVisit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsSpecialAccess")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisitorIpHash")
                        .HasColumnType("text");

                    b.Property<string>("VisitorUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VisitorUserId")
                        .HasDatabaseName("IX_ProfileVisits_VisitorUserId");

                    b.HasIndex("ProfileUserId", "VisitedAtUtc")
                        .HasDatabaseName("IX_ProfileVisits_ProfileUserId_VisitedAt");

                    b.ToTable("ProfileVisits");
                });

            modelBuilder.Entity("diji_card_alt.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivateAccessPassword")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("diji_card_alt.Models.UserDefinitionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomDefinitionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("IX_UserDefinitionValues_DefinitionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserDefinitionValues_UserId");

                    b.HasIndex("UserId", "DefinitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserDefinitionValues_UserId_DefinitionId_Unique")
                        .HasFilter("\"DefinitionId\" != 11");

                    b.ToTable("UserDefinitionValues");
                });

            modelBuilder.Entity("diji_card_alt.Models.ProfileVisit", b =>
                {
                    b.HasOne("diji_card_alt.Models.User", "ProfileUser")
                        .WithMany()
                        .HasForeignKey("ProfileUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("diji_card_alt.Models.User", "VisitorUser")
                        .WithMany()
                        .HasForeignKey("VisitorUserId");

                    b.Navigation("ProfileUser");

                    b.Navigation("VisitorUser");
                });

            modelBuilder.Entity("diji_card_alt.Models.UserDefinitionValue", b =>
                {
                    b.HasOne("diji_card_alt.Models.Definition", null)
                        .WithMany("UserDefinitionValues")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("diji_card_alt.Models.Definition", b =>
                {
                    b.Navigation("UserDefinitionValues");
                });
#pragma warning restore 612, 618
        }
    }
}
